ON_GREY00 = 0
ON_GREY01 = 238
ON_GREY02 = 239
ON_GREY03 = 59
ON_GREY04 = 145
ON_GREY05 = 152
ON_GREY06 = 188
ON_GREY07 = 15
ON_RED = 203
ON_ORANGE = 209
ON_YELLOW = 221
ON_GREEN = 114
ON_TEAL = 73
ON_BLUE = 68
ON_PURPLE = 176
ON_BROWN = 137
ON_WHITE = 15

# Segments colors.
USERATHOST_BG = ON_GREY02
USERATHOST_FG = ON_GREY04

SSH_BG = ON_TEAL
SSH_FG = ON_GREY01

CURRENTDIR_BG = ON_GREY01
CURRENTDIR_FG = ON_GREY05

READONLY_BG = ON_GREY01
READONLY_FG = ON_RED

EXITCODE_BG = ON_GREY01
EXITCODE_FG = ON_RED

PADDING_BG = ON_GREY00

GIT_UNTRACKED_FILES_BG = ON_GREY01
GIT_UNTRACKED_FILES_FG = ON_RED
GIT_CHANGES_NOT_STAGED_BG = ON_GREY02
GIT_CHANGES_NOT_STAGED_FG = ON_ORANGE
GIT_ALL_CHANGES_STAGED_BG = ON_GREY03
GIT_ALL_CHANGES_STAGED_FG = ON_YELLOW
GIT_CLEAN_BG = ON_GREY01
GIT_CLEAN_FG = ON_GREEN

VENV_BG = ON_BLUE
VENV_FG = ON_GREY00

JOBS_BG = ON_PURPLE
JOBS_FG = ON_GREY00

TIME_BG = ON_GREY00
TIME_FG = ON_GREY03